services:
 OpenKudo\Domain\Projection\Kudo\ThankYouReadModel:
    arguments: ['@doctrine.dbal.default_connection']
 OpenKudo\Domain\Projection\Person\PersonReadModel:
    arguments: ['@doctrine.dbal.default_connection']